import { Badge, Button, Card, Text } from "@shopify/polaris";
import { useCallback, useEffect, useState } from "react";
import type { AuthenticatedRequest } from "../../api";
import type { ProductDetail } from "./types";

type Props = { productId: string; request: AuthenticatedRequest; onError: (message: string) => void; onBack: () => void };
const stars = (rating: number) => "★".repeat(rating) + "☆".repeat(5 - rating);
export function ProductDetailPanel({ productId, request, onError, onBack }: Props) {
  const [product, setProduct] = useState<ProductDetail | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { setProduct(await request<ProductDetail>(`/api/admin/products/${productId}`)); } catch (issue) { onError((issue as Error).message); } finally { setLoading(false); } }, [onError, productId, request]);
  useEffect(() => { void load(); }, [load]);
  if (loading || !product) return <div className="tmr-empty-state"><Text as="p">Loading product reviews…</Text></div>;
  return <div className="tmr-product-workspace"><Button variant="plain" onClick={onBack}>← Back to products</Button><div className="tmr-product-detail-header"><div><div className="tmr-eyebrow">PRODUCT MANAGEMENT</div><Text as="h1" variant="headingLg">{product.title_snapshot || `Product #${product.shopify_product_id}`}</Text><Text as="p" tone="subdued">Product ID: {product.shopify_product_id}</Text></div><Badge tone="success">Active</Badge></div><div className="tmr-product-stats"><div><Text as="p" tone="subdued">Total reviews</Text><Text as="p" variant="headingLg">{product.review_count}</Text></div><div><Text as="p" tone="subdued">Published reviews</Text><Text as="p" variant="headingLg">{product.published_count}</Text></div><div><Text as="p" tone="subdued">Average rating</Text><Text as="p" variant="headingLg">{product.average_rating ? `${product.average_rating.toFixed(1)} / 5` : "—"}</Text></div></div><Card padding="0"><div className="tmr-product-reviews-heading"><Text as="h2" variant="headingMd">Product reviews</Text><Text as="p" tone="subdued">{product.review_count} total</Text></div>{product.reviews.map((review) => <article className="tmr-product-review-row" key={review.id}><div><Text as="p" fontWeight="semibold">{review.author_name}</Text><Text as="p" tone="subdued">{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(review.created_at))}{review.verified_purchase ? " · Verified purchase" : ""}</Text></div><div><div className="tmr-rating">{stars(review.rating)}</div>{review.title && <Text as="p" fontWeight="semibold">{review.title}</Text>}<Text as="p">{review.body}</Text>{review.reply_body && <Text as="p" tone="subdued">Store reply: {review.reply_body}</Text>}</div><Badge tone={review.status === "published" ? "success" : review.status === "pending" ? "attention" : "critical"}>{review.status}</Badge></article>)}{!product.reviews.length && <div className="tmr-empty-state"><Text as="p">No reviews for this product yet.</Text></div>}</Card></div>;
}
