import "@shopify/polaris/build/esm/styles.css";
import { AppProvider, Badge, Button, Card, DataTable, Layout, Page, Tabs, Text, TextField } from "@shopify/polaris";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { useAppBridge } from "@shopify/app-bridge-react";

type Review = { id:string; rating:number; author_name:string; body:string; status:string; verified_purchase:boolean; shopify_product_id:string; reply_body?:string };
type ApiError = { error?: string };
type ReviewResponse = { reviews: Review[] };
const copy = { en:{reviews:"Reviews",settings:"Settings",deliveries:"Test deliveries",approve:"Publish",hide:"Hide",deleted:"Delete",reply:"Reply",empty:"No reviews yet."}, zh:{reviews:"评价管理",settings:"设置",deliveries:"测试邀评",approve:"发布",hide:"隐藏",deleted:"删除",reply:"回复",empty:"暂时没有评价。"} };

function Admin() {
  const [language,setLanguage]=useState<"en"|"zh">("en"); const [tab,setTab]=useState(0); const [reviews,setReviews]=useState<Review[]>([]); const [error,setError]=useState(""); const c=copy[language];
  const shopify=useAppBridge();
  const request=useCallback(async<T,>(path:string,options?:RequestInit):Promise<T>=>{ const token=await shopify.idToken(); const response=await fetch(path,{...options,headers:{"content-type":"application/json",authorization:`Bearer ${token}`,...(options?.headers ?? {})}}); if(!response.ok) { const payload=await response.json().catch(()=>({error:"Request failed"})) as ApiError; throw new Error(payload.error ?? "Request failed"); } return response.json() as Promise<T>; },[shopify]);
  const load=useCallback(()=>request<ReviewResponse>("/api/admin/reviews").then((data)=>setReviews(data.reviews)).catch((issue:Error)=>setError(issue.message)),[request]); useEffect(()=>{load();},[load]);
  const moderate=async(id:string,status:string)=>{ try{await request(`/api/admin/reviews/${id}`,{method:"PATCH",body:JSON.stringify({status})});load();}catch(issue){setError((issue as Error).message);} };
  const rows=useMemo(()=>reviews.map((review)=>[review.author_name,`${review.rating}/5`,review.body,<Badge tone={review.status==="published"?"success":review.status==="pending"?"attention":"critical"}>{review.status}</Badge>,review.verified_purchase?"✓":"—",<span style={{display:"flex",gap:8}}><Button size="slim" onClick={()=>moderate(review.id,"published")}>{c.approve}</Button><Button size="slim" onClick={()=>moderate(review.id,"hidden")}>{c.hide}</Button></span>]),[reviews,c]);
  return <AppProvider i18n={{}}><Page title="Trust Me Review" subtitle="Shopify review management"><Layout><Layout.Section><Tabs tabs={[{id:"reviews",content:c.reviews},{id:"settings",content:c.settings},{id:"deliveries",content:c.deliveries}]} selected={tab} onSelect={setTab}/></Layout.Section>{error&&<Layout.Section><Card><Text as="p" tone="critical">{error}</Text></Card></Layout.Section>}{tab===0&&<Layout.Section><Card><DataTable columnContentTypes={["text","numeric","text","text","text","text"]} headings={["Customer","Rating","Review","Status","Verified","Actions"]} rows={rows}/>{!rows.length&&<Text as="p">{c.empty}</Text>}</Card></Layout.Section>}{tab===1&&<Layout.Section><Card><Text as="h2" variant="headingMd">{c.settings}</Text><TextField label="Review request delay (days)" type="number" value="14" onChange={()=>{}} autoComplete="off" helpText="Settings are persisted through the API after the production app is connected."/></Card></Layout.Section>}{tab===2&&<Layout.Section><Card><Text as="p">Test invitations appear here after fulfilled development-store orders are processed. No customer email is sent in V1.</Text></Card></Layout.Section>}</Layout></Page></AppProvider>;
}
function Invitation() { const token=location.pathname.split("/").pop() ?? ""; const [message,setMessage]=useState(""); const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const fields=new FormData(event.currentTarget);const response=await fetch(`/api/invitations/${token}/reviews`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rating:Number(fields.get("rating")),authorName:String(fields.get("authorName")??""),title:String(fields.get("title")??""),body:String(fields.get("body")??"")})});setMessage(response.ok?"Thank you. Your review is awaiting approval.":"This invitation is invalid or has already been used.");};return <AppProvider i18n={{}}><Page title="Share your review"><Card><form onSubmit={submit} style={{display:"grid",gap:12}}><TextField label="Name" name="authorName" autoComplete="name" onChange={()=>{}}/><TextField label="Rating (1-5)" name="rating" type="number" min={1} max={5} value="5" onChange={()=>{}} autoComplete="off"/><TextField label="Title" name="title" autoComplete="off" onChange={()=>{}}/><TextField label="Review" name="body" multiline autoComplete="off" onChange={()=>{}}/><Button submit variant="primary">Submit review</Button>{message&&<Text as="p">{message}</Text>}</form></Card></Page></AppProvider>; }
createRoot(document.getElementById("root")!).render(location.pathname.startsWith("/review/")?<Invitation/>:<Admin/>);
